<a href="https://colab.research.google.com/github/MartaJJ/zajecia_schedule_misp/blob/master/HousePrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive/')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive/


In [2]:
import pandas as pd
from sklearn.preprocessing import Imputer
from sklearn.linear_model import LinearRegression
import numpy
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn import preprocessing
from sklearn.ensemble import RandomForestRegressor


train = pd.read_csv('/content/drive/My Drive/train.csv', index_col= 'Id')
train.reset_index(drop=True, inplace=True)
print(train)

      MSSubClass MSZoning  LotFrontage  ...  SaleType SaleCondition SalePrice
0             60       RL         65.0  ...        WD        Normal    208500
1             20       RL         80.0  ...        WD        Normal    181500
2             60       RL         68.0  ...        WD        Normal    223500
3             70       RL         60.0  ...        WD       Abnorml    140000
4             60       RL         84.0  ...        WD        Normal    250000
...          ...      ...          ...  ...       ...           ...       ...
1455          60       RL         62.0  ...        WD        Normal    175000
1456          20       RL         85.0  ...        WD        Normal    210000
1457          70       RL         66.0  ...        WD        Normal    266500
1458          20       RL         68.0  ...        WD        Normal    142125
1459          20       RL         75.0  ...        WD        Normal    147500

[1460 rows x 80 columns]


In [0]:
def preprocess_data(data):
  numerical, categorical = [], []
  for i in data.columns:
      if data[i].dtype == 'object':
          categorical.append(i)
      else:
          numerical.append(i)
  
  numerical.remove('MSSubClass')
  categorical.append('MSSubClass')
  train_num = data[numerical]

  imputer = Imputer(missing_values='NaN' , strategy='median' , axis = 0)
  imputer = imputer.fit(train_num)
  train_num = imputer.transform(train_num)

  return train_num

In [4]:
y_train = train[['SalePrice']]
train.drop('SalePrice' , axis = 1 , inplace=True)

X_train = preprocess_data(train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [5]:
print(X_train)

[[6.500e+01 8.450e+03 7.000e+00 ... 0.000e+00 2.000e+00 2.008e+03]
 [8.000e+01 9.600e+03 6.000e+00 ... 0.000e+00 5.000e+00 2.007e+03]
 [6.800e+01 1.125e+04 7.000e+00 ... 0.000e+00 9.000e+00 2.008e+03]
 ...
 [6.600e+01 9.042e+03 7.000e+00 ... 2.500e+03 5.000e+00 2.010e+03]
 [6.800e+01 9.717e+03 5.000e+00 ... 0.000e+00 4.000e+00 2.010e+03]
 [7.500e+01 9.937e+03 5.000e+00 ... 0.000e+00 6.000e+00 2.008e+03]]


In [0]:
X_train , X_test , y_train , y_test=  train_test_split(X_train , y_train , test_size= 0.2 , random_state=123)

In [7]:
reg = RandomForestRegressor().fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


In [8]:
y_pred = reg.predict(X_test)

print(mean_squared_error(y_test, y_pred))

763307645.4512138


In [0]:
test = pd.read_csv('/content/drive/My Drive/test.csv', index_col= 'Id')
test_labels = test.index
test.reset_index(drop=True, inplace=True)

# print(test)

In [10]:
X = preprocess_data(test)
y = reg.predict(X)

result = numpy.vstack((test_labels, y)).T
result = numpy.vstack(([["Id", "SalePrice"]], result))
df = pd.DataFrame(result)
df.columns = df.iloc[0]
df=df[1:]
print(df)
df.to_csv("results.csv", index=False)

0         Id SalePrice
1     1461.0  124100.0
2     1462.0  152500.0
3     1463.0  172020.0
4     1464.0  185050.0
5     1465.0  190478.5
...      ...       ...
1455  2915.0   81300.0
1456  2916.0   91250.0
1457  2917.0  161910.0
1458  2918.0  106250.0
1459  2919.0  226240.0

[1459 rows x 2 columns]


/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)
